# Generated by Django 3.0.6 on 2020-06-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cvitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvitem',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
